# Generated by Django 2.0.7 on 2019-11-24 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accolade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Accolade', models.IntegerField(choices=[('0', 'First Team'), ('1', 'Second Team'), ('2', 'Third Team'), ('3', 'Rookie Team'), ('4', 'Honorable Mention'), ('5', 'Freshman Team')])),
            ],
            options={
                'verbose_name': 'Accolade',
                'verbose_name_plural': 'Accolade',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('College League', models.IntegerField(choices=[('0', 'America East Conference'), ('1', ''), ('2', ''), ('3', ''), ('4', ''), ('5', ''), ('6', ''), ('7', ''), ('8', ''), ('9', ''), ('10', ''), ('11', ''), ('12', ''), ('13', ''), ('14', ''), ('15', ''), ('16', ''), ('17', ''), ('18', ''), ('19', ''), ('20', ''), ('21', ''), ('22', ''), ('23', ''), ('24', '')])),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'College',
            },
        ),
        migrations.CreateModel(
            name='High_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('location_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('location_long', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'verbose_name': 'high_school',
                'verbose_name_plural': 'high_school',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First Name', models.CharField(max_length=20)),
                ('Last Name', models.CharField(max_length=20)),
                ('Height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('Weight', models.IntegerField(blank=True, null=True)),
                ('State/Country', models.CharField(blank=True, max_length=20, null=True)),
                ('Hometown', models.CharField(blank=True, max_length=20, null=True)),
                ('College', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.College')),
                ('High School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.High_school')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Potential Strats', models.IntegerField(blank=True, null=True)),
                ('GP', models.IntegerField(blank=True, null=True)),
                ('GS', models.IntegerField(blank=True, null=True)),
                ('Is_starter', models.NullBooleanField()),
                ('Position1', models.IntegerField(choices=[(0, 'Forward'), (1, 'Midfielder'), (2, 'Defender'), (3, 'Back'), (4, 'Goalkeeper')], null=True)),
                ('Position2', models.IntegerField(choices=[(0, 'Forward'), (1, 'Midfielder'), (2, 'Defender'), (3, 'Back'), (4, 'Goalkeeper')], null=True)),
                ('Position3', models.IntegerField(choices=[(0, 'Forward'), (1, 'Midfielder'), (2, 'Defender'), (3, 'Back'), (4, 'Goalkeeper')], null=True)),
                ('Roster_Year', models.IntegerField(blank=True, null=True)),
                ('Year', models.IntegerField(blank=True, null=True)),
                ('Player_num', models.IntegerField(blank=True, null=True)),
                ('bio_link', models.CharField(blank=True, max_length=50, null=True)),
                ('College', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.College')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Player')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Record',
            },
        ),
        migrations.AddField(
            model_name='accolade',
            name='College',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.College'),
        ),
        migrations.AddField(
            model_name='accolade',
            name='Player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Player'),
        ),
    ]
