# Generated by Django 2.0.7 on 2019-11-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='high_school',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
