# Generated by Django 2.0.7 on 2019-11-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20191125_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='high_school',
            name='location_lat',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='high_school',
            name='location_long',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
