# Generated by Django 2.0.7 on 2019-11-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20191125_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Hometown',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
