# Generated by Django 2.0.7 on 2019-11-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20191125_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='First Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Last Name',
            new_name='last_name',
        ),
    ]
