# Generated by Django 2.0.7 on 2019-11-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20191125_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='College League',
            new_name='College_League',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='Potential Strats',
            new_name='Potential_Strats',
        ),
    ]
