# Generated by Django 2.0.7 on 2019-11-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20191125_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='High School',
            new_name='High_School',
        ),
    ]
